"""
Jupiter-X Constants and Parameter Definitions

This module defines all constants, model IDs, and parameter mappings
for Roland Jupiter-X synthesizer integration.
"""

from __future__ import annotations

# MIDI Constants
JUPITER_X_MANUFACTURER_ID = 0x41  # Roland
JUPITER_X_MODEL_ID = 0x64  # Jupiter-X model ID
JUPITER_X_DEVICE_ID_DEFAULT = 0x10

# SysEx Commands
SYSEX_CMD_PARAMETER_CHANGE = 0x12
SYSEX_CMD_BULK_DUMP_REQUEST = 0x11
SYSEX_CMD_DATA_REQUEST = 0x10
SYSEX_CMD_BULK_DUMP = 0x40

# NRPN Parameter Ranges (MSB)
NRPN_SYSTEM_PARAMS = range(0x00, 0x10)  # System/Global (0-15)
NRPN_PART_PARAMS = range(0x10, 0x30)  # Parts 0-15 (16-47)
NRPN_ENGINE_PARAMS = range(0x30, 0x40)  # Engine params (48-63)
NRPN_EFFECTS_PARAMS = range(0x40, 0x50)  # Effects (64-79)
NRPN_ARPEGGIATOR_PARAMS = range(0x50, 0x60)  # Arpeggiator (80-95)
NRPN_LFO_MODULATION = range(0x60, 0x70)  # LFO/Modulation (96-111)
NRPN_ADVANCED_FEATURES = range(0x70, 0x80)  # Advanced (112-127)

# Engine Types
ENGINE_ANALOG = 0
ENGINE_DIGITAL = 1
ENGINE_FM = 2
ENGINE_EXTERNAL = 3

ENGINE_NAMES = {
    ENGINE_ANALOG: "Analog",
    ENGINE_DIGITAL: "Digital",
    ENGINE_FM: "FM",
    ENGINE_EXTERNAL: "External",
}

# Jupiter-X Parameter Addresses (3-byte addresses)
# Format: 0xAA BB CC where AA=address_high, BB=address_mid, CC=address_low

# System Parameters
ADDR_MASTER_VOLUME = (0x00, 0x00, 0x00)
ADDR_MASTER_TUNE = (0x00, 0x00, 0x01)
ADDR_MASTER_TRANSPOSE = (0x00, 0x00, 0x02)
ADDR_SYSTEM_CLOCK = (0x00, 0x00, 0x03)

# Part Parameters (Base address + part offset)
PART_BASE_ADDR = (0x10, 0x00, 0x00)  # Part 0
PART_ADDR_OFFSET = (0x00, 0x01, 0x00)  # Offset per part

# Engine Parameters within each part
ENGINE_BASE_OFFSET = 0x20  # Within part address space

# Analog Engine Parameters (relative to engine base)
ANALOG_OSC1_WAVEFORM = 0x00
ANALOG_OSC1_COARSE_TUNE = 0x01
ANALOG_OSC1_FINE_TUNE = 0x02
ANALOG_OSC1_LEVEL = 0x03
ANALOG_OSC1_SUPERSAW_SPREAD = 0x04

ANALOG_OSC2_WAVEFORM = 0x10
ANALOG_OSC2_COARSE_TUNE = 0x11
ANALOG_OSC2_FINE_TUNE = 0x12
ANALOG_OSC2_LEVEL = 0x13
ANALOG_OSC2_DETUNE = 0x14
ANALOG_OSC2_RING_MOD = 0x15

ANALOG_FILTER_TYPE = 0x20
ANALOG_FILTER_CUTOFF = 0x21
ANALOG_FILTER_RESONANCE = 0x22
ANALOG_FILTER_ENVELOPE_AMOUNT = 0x23

ANALOG_AMP_ATTACK = 0x30
ANALOG_AMP_DECAY = 0x31
ANALOG_AMP_SUSTAIN = 0x32
ANALOG_AMP_RELEASE = 0x33

ANALOG_FILTER_ATTACK = 0x40
ANALOG_FILTER_DECAY = 0x41
ANALOG_FILTER_SUSTAIN = 0x42
ANALOG_FILTER_RELEASE = 0x43

# Digital Engine Parameters
DIGITAL_WAVETABLE_POSITION = 0x00
DIGITAL_MORPH_AMOUNT = 0x01
DIGITAL_FORMANT_SHIFT = 0x02
DIGITAL_BIT_CRUSH = 0x03
DIGITAL_SAMPLE_RATE_REDUCTION = 0x04

# FM Engine Parameters
FM_ALGORITHM = 0x00
FM_FEEDBACK = 0x01
FM_OPERATOR_RATIO_BASE = 0x10  # 6 operators × parameters
FM_OPERATOR_LEVEL_BASE = 0x20
FM_OPERATOR_ATTACK_BASE = 0x30
FM_OPERATOR_DECAY_BASE = 0x40
FM_OPERATOR_SUSTAIN_BASE = 0x50
FM_OPERATOR_RELEASE_BASE = 0x60

# External Engine Parameters
EXTERNAL_SAMPLE_SELECT = 0x00
EXTERNAL_START_POINT = 0x01
EXTERNAL_END_POINT = 0x02
EXTERNAL_LOOP_MODE = 0x03
EXTERNAL_PITCH_SHIFT = 0x04
EXTERNAL_TIME_STRETCH = 0x05

# Effects Parameters
EFFECTS_REVERB_TYPE = (0x40, 0x00, 0x00)
EFFECTS_REVERB_LEVEL = (0x40, 0x00, 0x01)
EFFECTS_REVERB_TIME = (0x40, 0x00, 0x02)

EFFECTS_CHORUS_TYPE = (0x40, 0x01, 0x00)
EFFECTS_CHORUS_LEVEL = (0x40, 0x01, 0x01)
EFFECTS_CHORUS_RATE = (0x40, 0x01, 0x02)

EFFECTS_DELAY_TYPE = (0x40, 0x02, 0x00)
EFFECTS_DELAY_LEVEL = (0x40, 0x02, 0x01)
EFFECTS_DELAY_TIME = (0x40, 0x02, 0x02)

EFFECTS_DISTORTION_TYPE = (0x40, 0x03, 0x00)
EFFECTS_DISTORTION_LEVEL = (0x40, 0x03, 0x01)
EFFECTS_DISTORTION_DRIVE = (0x40, 0x03, 0x02)

# Arpeggiator Parameters
ARPEGGIATOR_GRID_BASE = (0x50, 0x00, 0x00)  # 8x8 grid data
ARPEGGIATOR_TEMPO = (0x50, 0x01, 0x00)
ARPEGGIATOR_GATE_TIME = (0x50, 0x01, 0x01)
ARPEGGIATOR_SWING = (0x50, 0x01, 0x02)
ARPEGGIATOR_OCTAVE_RANGE = (0x50, 0x01, 0x03)
ARPEGGIATOR_PATTERN_LENGTH = (0x50, 0x01, 0x04)

# Parameter Ranges
PARAM_RANGE_0_127 = (0, 127)
PARAM_RANGE_0_255 = (0, 255)
PARAM_RANGE_NEGATIVE_63_63 = (-63, 63)
PARAM_RANGE_0_16383 = (0, 16383)  # 14-bit NRPN

# Waveform Types for Analog Engine
WAVEFORM_SAWTOOTH = 0
WAVEFORM_SQUARE = 1
WAVEFORM_TRIANGLE = 2
WAVEFORM_SINE = 3
WAVEFORM_NOISE = 4

# Jupiter-X Enhanced Waveforms
WAVEFORM_RANDOM_SH = 5  # Random Sample & Hold
WAVEFORM_TRAPEZOID = 6  # Trapezoid wave

WAVEFORM_NAMES = {
    WAVEFORM_SAWTOOTH: "Sawtooth",
    WAVEFORM_SQUARE: "Square",
    WAVEFORM_TRIANGLE: "Triangle",
    WAVEFORM_SINE: "Sine",
    WAVEFORM_NOISE: "Noise",
    WAVEFORM_RANDOM_SH: "Random S&H",
    WAVEFORM_TRAPEZOID: "Trapezoid",
}

# Filter Types
FILTER_LPF = 0
FILTER_HPF = 1
FILTER_BPF = 2
FILTER_NOTCH = 3

FILTER_NAMES = {
    FILTER_LPF: "Low Pass",
    FILTER_HPF: "High Pass",
    FILTER_BPF: "Band Pass",
    FILTER_NOTCH: "Notch",
}

# Arpeggiator Grid Size
ARPEGGIATOR_GRID_WIDTH = 8
ARPEGGIATOR_GRID_HEIGHT = 8

# Default Parameter Values
DEFAULT_MASTER_VOLUME = 100
DEFAULT_MASTER_TUNE = 0
DEFAULT_MASTER_TRANSPOSE = 0

# Part Default Values
DEFAULT_PART_VOLUME = 100
DEFAULT_PART_PAN = 64
DEFAULT_PART_COARSE_TUNE = 0
DEFAULT_PART_FINE_TUNE = 0

# Engine Default Values
DEFAULT_ENGINE_LEVEL = 100
DEFAULT_OSC_WAVEFORM = WAVEFORM_SAWTOOTH
DEFAULT_FILTER_TYPE = FILTER_LPF
DEFAULT_FILTER_CUTOFF = 64
DEFAULT_FILTER_RESONANCE = 0

# Envelope Default Values
DEFAULT_ATTACK = 0
DEFAULT_DECAY = 64
DEFAULT_SUSTAIN = 127
DEFAULT_RELEASE = 32

# Effects Default Values
DEFAULT_REVERB_TYPE = 1  # Hall
DEFAULT_REVERB_LEVEL = 40
DEFAULT_REVERB_TIME = 64

DEFAULT_CHORUS_TYPE = 1
DEFAULT_CHORUS_LEVEL = 0
DEFAULT_CHORUS_RATE = 64

# Arpeggiator Default Values
DEFAULT_ARPEGGIATOR_TEMPO = 120
DEFAULT_ARPEGGIATOR_GATE_TIME = 80  # 80%
DEFAULT_ARPEGGIATOR_SWING = 50  # 50%
DEFAULT_ARPEGGIATOR_OCTAVE_RANGE = 1
DEFAULT_ARPEGGIATOR_PATTERN_LENGTH = 1
