"""
NRPN/SYSEX Mappings for S.Art2 Articulation System.

Contains all articulation mappings indexed by NRPN MSB/LSB values.
This module is extracted from articulation_controller.py for better organization.
"""
from __future__ import annotations



# NRPN MSB categories
MSB_CATEGORIES = {
    1: "common",
    2: "dynamics",
    3: "wind_sax",
    4: "wind_brass",
    5: "wind_woodwind",
    6: "strings_bow",
    7: "strings_pluck",
    8: "guitar",
    9: "vocal",
    10: "synth",
    11: "percussion",
    12: "ethnic",
    13: "effects",
    14: "piano",
    15: "bass",
    16: "organ",
    17: "ethnic_world",
}


# Complete NRPN to Articulation mapping (333 articulations)
NRPN_ARTICULATION_MAP: dict[tuple[int, int], str] = {
    # Common articulations (MSB 1)
    (1, 0): "normal",
    (1, 1): "legato",
    (1, 2): "staccato",
    (1, 3): "bend",
    (1, 4): "vibrato",
    (1, 5): "breath",
    (1, 6): "glissando",
    (1, 7): "growl",
    (1, 8): "flutter",
    (1, 9): "trill",
    (1, 10): "pizzicato",
    (1, 11): "grace",
    (1, 12): "shake",
    (1, 13): "fall",
    (1, 14): "doit",
    (1, 15): "tongue_slap",
    (1, 16): "harmonics",
    (1, 17): "hammer_on",
    (1, 18): "pull_off",
    (1, 19): "key_off",
    (1, 20): "marcato",
    (1, 21): "detache",
    (1, 22): "sul_ponticello",
    (1, 23): "scoop",
    (1, 24): "rip",
    (1, 25): "portamento",
    (1, 26): "swell",
    (1, 27): "accented",
    (1, 28): "bow_up",
    (1, 29): "bow_down",
    (1, 30): "col_legno",
    (1, 31): "up_bend",
    (1, 32): "down_bend",
    (1, 33): "smear",
    (1, 34): "flip",
    (1, 35): "straight",
    # Dynamics (MSB 2)
    (2, 0): "ppp",
    (2, 1): "pp",
    (2, 2): "p",
    (2, 3): "mp",
    (2, 4): "mf",
    (2, 5): "f",
    (2, 6): "ff",
    (2, 7): "fff",
    (2, 8): "crescendo",
    (2, 9): "diminuendo",
    (2, 10): "sfz",
    (2, 11): "rfz",
    # Wind - Sax (MSB 3)
    (3, 0): "growl_wind",
    (3, 1): "flutter_wind",
    (3, 2): "tongue_slap_wind",
    (3, 3): "smear_wind",
    (3, 4): "flip_wind",
    (3, 5): "scoop_wind",
    (3, 6): "rip_wind",
    (3, 7): "double_tongue",
    (3, 8): "triple_tongue",
    # Wind - Brass (MSB 4)
    (4, 0): "muted_brass",
    (4, 1): "cup_mute",
    (4, 2): "harmon_mute",
    (4, 3): "stopped",
    (4, 4): "scoop_brass",
    (4, 5): "lip_trill",
    (4, 6): "shake_brass",
    (4, 7): "drop_brass",
    (4, 8): "doit_brass",
    (4, 9): "fall_brass",
    # Strings - Bow (MSB 7)
    (7, 0): "pizzicato_strings",
    (7, 1): "harmonics_strings",
    (7, 2): "sul_ponticello_strings",
    (7, 3): "bow_up_strings",
    (7, 4): "bow_down_strings",
    (7, 5): "col_legno_strings",
    (7, 6): "portamento_strings",
    (7, 7): "spiccato",
    (7, 8): "tremolando",
    (7, 9): "sautille",
    (7, 10): "martele",
    (7, 11): "ricochet",
    (7, 12): "flautando",
    (7, 13): "sul_g",
    (7, 14): "con_sordino",
    (7, 15): "senza_sordino",
    (7, 16): "tremolo",
    (7, 17): "tremolo_sordino",
    (7, 18): "portamento_fast",
    (7, 19): "portamento_slow",
    (7, 20): "sul_tasto",
    (7, 21): "punto",
    # Strings - Pluck (MSB 8)
    (8, 0): "pizzicato_snap",
    (8, 1): "pizzicato_left",
    (8, 2): "pizzicato_right",
    (8, 3): "pizzicato_chord",
    (8, 4): "barto_k",
    (8, 5): "gyro_pizz",
    (8, 6): "harmonic_pizz",
    (8, 7): "muted_pizz",
    (8, 8): "vibrato_pizz",
    (8, 9): "gliss_pizz",
    (8, 10): "thumb_pizz",
    (8, 11): "slap_pizz",
    (8, 12): "pop_pizz",
    (8, 13): "tap_pizz",
    (8, 14): "scratch_pizz",
    # Guitar (MSB 9)
    (9, 0): "slide_up_gtr",
    (9, 1): "slide_down_gtr",
    (9, 2): "bend_gtr",
    (9, 3): "bend_release_gtr",
    (9, 4): "pre_bend",
    (9, 5): "harmonics_natural",
    (9, 6): "harmonics_artificial",
    (9, 7): "harmonics_pinch",
    (9, 8): "tapping_gtr",
    (9, 9): "slap_gtr",
    (9, 10): "pop_gtr",
    (9, 11): "mute_gtr",
    (9, 12): "cut_noise",
    (9, 13): "fret_noise",
    (9, 14): "string_noise",
    (9, 15): "body_hit_gtr",
    (9, 16): "hammer_on_gtr",
    (9, 17): "pull_off_gtr",
    (9, 18): "vibrato_gtr",
    (9, 19): "wide_vibrato",
    (9, 20): "palm_mute_gtr",
    (9, 21): "harmonic_tap",
    (9, 22): "tremolo_gtr",
    (9, 23): "arpeggio_up",
    (9, 24): "arpeggio_down",
    # Vocal (MSB 10)
    (10, 0): "vocal_breath",
    (10, 1): "vocal_attack",
    (10, 2): "vocal_fry",
    (10, 3): "falsetto",
    (10, 4): "chest_voice",
    (10, 5): "head_voice",
    (10, 6): "mixed_voice",
    (10, 7): "whisper",
    (10, 8): "shout",
    (10, 9): "scream",
    (10, 10): "growl_vocal",
    (10, 11): "vibrato_vocal",
    (10, 12): "straight_tone",
    (10, 13): "scoop_vocal",
    (10, 14): "fall_vocal",
    (10, 15): "turn_vocal",
    (10, 16): "mordent_vocal",
    (10, 17): "trill_vocal",
    (10, 18): "glissando_vocal",
    (10, 19): "portamento_vocal",
    # Synth (MSB 11)
    (11, 0): "synth_attack",
    (11, 1): "synth_decay",
    (11, 2): "synth_sustain",
    (11, 3): "synth_release",
    (11, 4): "filter_sweep",
    (11, 5): "filter_snap",
    (11, 6): "lfo_sync",
    (11, 7): "lfo_free",
    (11, 8): "glide",
    (11, 9): "legato_synth",
    (11, 10): "staccato_synth",
    (11, 11): "trig_synth",
    (11, 12): "gate_synth",
    (11, 13): "accent_synth",
    (11, 14): "tie_synth",
    # Percussion (MSB 12)
    (12, 0): "perc_attack",
    (12, 1): "perc_decay",
    (12, 2): "rim_shot",
    (12, 3): "cross_stick",
    (12, 4): "buzz_roll",
    (12, 5): "press_roll",
    (12, 6): "flam",
    (12, 7): "drag",
    (12, 8): "ruff",
    (12, 9): "diddle",
    (12, 10): "bounce",
    (12, 11): "dead_stroke",
    (12, 12): "tap_perc",
    (12, 13): "slap_perc",
    (12, 14): "pop_perc",
    (12, 15): "mute_perc",
    (12, 16): "open_perc",
    (12, 17): "closed_perc",
    (12, 18): "choke_perc",
    (12, 19): "sustain_perc",
    # Ethnic (MSB 13)
    (13, 0): "ethnic_attack",
    (13, 1): "ethnic_decay",
    (13, 2): "bend_ethnic",
    (13, 3): "vibrato_ethnic",
    (13, 4): "tremolo_ethnic",
    (13, 5): "harmonic_ethnic",
    (13, 6): "percussive_ethnic",
    (13, 7): "breath_ethnic",
    (13, 8): "slide_ethnic",
    (13, 9): "gliss_ethnic",
    (13, 10): "trill_ethnic",
    (13, 11): "mordent_ethnic",
    (13, 12): "turn_ethnic",
    (13, 13): "grace_ethnic",
    (13, 14): "accent_ethnic",
    (13, 15): "staccato_ethnic",
    (13, 16): "tenuto_ethnic",
    (13, 17): "marcato_ethnic",
    # Effects (MSB 14)
    (14, 0): "fx_sweep_up",
    (14, 1): "fx_sweep_down",
    (14, 2): "fx_noise",
    (14, 3): "fx_hit",
    (14, 4): "fx_rise",
    (14, 5): "fx_fall",
    (14, 6): "fx_boom",
    (14, 7): "fx_crash",
    (14, 8): "fx_slam",
    (14, 9): "fx_scrape",
    (14, 10): "fx_click",
    (14, 11): "fx_pop",
    # Piano (MSB 15)
    (15, 0): "soft_pedal",
    (15, 1): "sustain_pedal",
    (15, 2): "sostenuto_pedal",
    (15, 3): "una_corda",
    (15, 4): "tre_corde",
    (15, 5): "key_off_early",
    (15, 6): "key_off_late",
    (15, 7): "key_off_noise",
    (15, 8): "duplex_scale",
    (15, 9): "string_resonance",
    (15, 10): "damper_noise",
    (15, 11): "hammer_noise",
    (15, 12): "pedal_up",
    (15, 13): "pedal_down",
    (15, 14): "soft_lift",
    (15, 15): "sustain_lift",
    (15, 16): "agoge",
    (15, 17): "portamento_piano",
    (15, 18): "legato_pedal",
    (15, 19): "mute_staccato",
    # Bass (MSB 16)
    (16, 0): "finger_style",
    (16, 1): "pick_style",
    (16, 2): "slap_bass",
    (16, 3): "pop_bass",
    (16, 4): "muted_bass",
    (16, 5): "open_string",
    (16, 6): "fret_noise_bass",
    (16, 7): "harmonic_bass",
    (16, 8): "glissando_bass",
    (16, 9): "slide_bass",
    (16, 10): "dead_note",
    (16, 11): "neck_position",
    (16, 12): "bridge_position",
    (16, 13): "pizzicato_bass",
    (16, 14): "tremolo_bass",
    (16, 15): "tap_bass",
    (16, 16): "raking",
    (16, 17): "semi_tone_harm",
    (16, 18): "pedal_point",
    (16, 19): "sub_bass",
    # Organ (MSB 17)
    (17, 0): "drawbar_organ",
    (17, 1): "percussive_organ",
    (17, 2): "click_organ",
    (17, 3): "rotary_organ",
    (17, 4): "leslie_slow",
    (17, 5): "leslie_fast",
    (17, 6): "vibrato_organ",
    (17, 7): "chorus_organ",
    (17, 8): "reverb_organ",
    (17, 9): "Organ_soft",
    (17, 10): "Organ_loud",
    (17, 11): "Organ_gospel",
    (17, 12): "Organ_jazzy",
    (17, 13): "Organ_rock",
    (17, 14): "Organ_full",
    # Ethnic World (MSB 18)
    (18, 0): "sitar_attack",
    (18, 1): "sitar_pluck",
    (18, 2): "sitar_bend",
    (18, 3): "tanpura_drone",
    (18, 4): "tabla_tom",
    (18, 5): "tabla_ti",
    (18, 6): "tabla_na",
    (18, 7): "tabla_ke",
    (18, 8): "dholak_roll",
    (18, 9): "dholak_tak",
    (18, 10): "didgeridoo_drone",
    (18, 11): "didgeridoo_rit",
    (18, 12): "berimbau_roll",
    (18, 13): "berimbau_clic",
    (18, 14): "kalimba_pluck",
    (18, 15): "kora_pluck",
    (18, 16): "guzheng_ply",
    (18, 17): "guzheng_gliss",
    (18, 18): "shakuhachi_breath",
    (18, 19): "shakuhachi_flip",
}


# Aliases for common articulations
ARTICULATION_ALIASES = {
    "norm": "normal",
    "norma": "normal",
    "leg": "legato",
    "legato": "legato",
    "stacc": "staccato",
    "staccato": "staccato",
    "vib": "vibrato",
    "vibrato": "vibrato",
    "harm": "harmonics",
    "harmonics": "harmonics",
    "hamm": "hammer_on",
    "hammer": "hammer_on",
    "pulloff": "pull_off",
    "pizz": "pizzicato",
    "pizzicato": "pizzicato",
    "trem": "tremolo",
    "tremolo": "tremolo",
    "gliss": "glissando",
    "glissando": "glissando",
    "growl": "growl",
    "flutter": "flutter",
    "trill": "trill",
    "swell": "swell",
    "cresc": "crescendo",
    "crescendo": "crescendo",
    "dim": "diminuendo",
    "diminuendo": "diminuendo",
    "mar": "marcato",
    "marcato": "marcato",
    "acc": "accented",
    "accented": "accented",
    "bend": "bend",
    "bend": "bend",
}


def get_articulation_from_nrpn(msb: int, lsb: int) -> str:
    """Get articulation name from NRPN MSB/LSB."""
    return NRPN_ARTICULATION_MAP.get((msb, lsb), "normal")


def get_nrpn_for_articulation(articulation: str) -> tuple[int, int]:
    """Get NRPN MSB/LSB for articulation name."""
    # Check aliases first
    canonical = ARTICULATION_ALIASES.get(articulation, articulation)

    for (msb, lsb), art in NRPN_ARTICULATION_MAP.items():
        if art == canonical:
            return (msb, lsb)

    # Check original
    for (msb, lsb), art in NRPN_ARTICULATION_MAP.items():
        if art == articulation:
            return (msb, lsb)

    return (1, 0)  # Default to 'normal'


def get_category_for_msb(msb: int) -> str:
    """Get category name for MSB."""
    return MSB_CATEGORIES.get(msb, "unknown")


__all__ = [
    "NRPN_ARTICULATION_MAP",
    "MSB_CATEGORIES",
    "ARTICULATION_ALIASES",
    "get_articulation_from_nrpn",
    "get_nrpn_for_articulation",
    "get_category_for_msb",
]
